"""Type stubs for the compiled ``caliper._core`` extension module (Rust)."""

__version__: str

# schema
def schema_version() -> str: ...
def core_version() -> str: ...
def default_record_json() -> str: ...
def normalize_record_json(text: str, /) -> str: ...
def validate_record_json(text: str, /) -> list[str]: ...

# statistics
def summarize(samples: list[float], /) -> dict[str, float]: ...
def cross_pass_cov(pass_medians: list[float], /) -> float | None: ...
def quantiles(samples: list[float], qs: list[float], /) -> list[float]: ...

# warm-up
def steady_state_index(
    times: list[float],
    window: int = ...,
    tol: float = ...,
    min_warm: int = ...,
) -> tuple[int, bool]: ...

# bench
def bench_replay(recording: str, opts_json: str, /) -> str: ...
def bench_replay_quantiles(
    recording: str, opts_json: str, quantiles: list[float], /
) -> list[float]: ...

# ptxas parsing
def parse_ptxas(text: str, /) -> str: ...

# occupancy
def theoretical_occupancy(
    arch: str,
    regs_per_thread: int,
    smem_bytes_per_block: int,
    threads_per_block: int,
    /,
) -> str | None: ...

# roofline
def roofline_analyze(
    arch: str,
    dtype: str,
    flops: float,
    bytes_hbm: float,
    seconds: float,
    /,
) -> str: ...
def peak_compute_tflops(arch: str, dtype: str, /) -> float | None: ...
def peak_hbm_gbps(arch: str, /) -> float | None: ...
def corpus_roofline_spec(
    kernel_key: str, shape_json: str, dtype: str | None = ..., /
) -> str | None: ...

# corpus targets
def resolve_corpus_target(name: str, /) -> str | None: ...
def corpus_targets() -> list[tuple[str, str, str]]: ...

# compare / thresholds
def compare_datasets(baseline_json: str, candidate_json: str, opts_json: str, /) -> str: ...

# doctor / fingerprint
def doctor_replay(recording: str, /) -> str: ...
def doctor_render_replay(recording: str, /) -> str: ...
def doctor_from_env() -> str: ...
def doctor_render_from_env() -> str: ...
def fingerprint_replay(recording: str, /) -> str: ...
def fingerprint_from_env() -> str: ...
def fingerprint_check(machine_json: str, /) -> str: ...
def fingerprint_is_complete(machine_json: str, /) -> bool: ...
def parse_nvcc_version(output: str, /) -> str | None: ...
def parse_ptxas_version(output: str, /) -> str | None: ...

# autotune cache key
def autotune_key(machine_json: str, kernel_source_hash: str, config_json: str, /) -> str: ...
def autotune_config_canonical(config_json: str, /) -> str: ...

# sweep spec
def expand_spec(spec_json: str, /) -> str: ...
def spec_pending(cells_json: str, done_keys_json: str, /) -> str: ...
def spec_cell_keys(cells_json: str, /) -> list[str]: ...

# shape libraries
def resolve_shape_library(name: str, /) -> str | None: ...
def shape_library_names() -> list[str]: ...

# selftest
def selftest_from_env(full: bool, /) -> str: ...
def selftest_assemble(
    machine_json: str, checks_json: str, not_validated_json: str = ..., /
) -> str: ...
def validate_selftest_json(text: str, /) -> list[str]: ...
