"""Type stubs for the compiled ``caliper._core`` extension module (Rust)."""

__version__: str

# schema
def schema_version() -> str: ...
def core_version() -> str: ...
def default_record_json() -> str: ...
def normalize_record_json(text: str, /) -> str: ...
def validate_record_json(text: str, /) -> list[str]: ...

# statistics
def summarize(samples: list[float], /) -> dict[str, float]: ...
def cross_pass_cov(pass_medians: list[float], /) -> float | None: ...

# warm-up
def steady_state_index(
    times: list[float],
    window: int = ...,
    tol: float = ...,
    min_warm: int = ...,
) -> tuple[int, bool]: ...

# bench
def bench_replay(recording: str, opts_json: str, /) -> str: ...

# ptxas parsing
def parse_ptxas(text: str, /) -> str: ...

# occupancy
def theoretical_occupancy(
    arch: str,
    regs_per_thread: int,
    smem_bytes_per_block: int,
    threads_per_block: int,
    /,
) -> str | None: ...

# roofline
def roofline_analyze(
    arch: str,
    dtype: str,
    flops: float,
    bytes_hbm: float,
    seconds: float,
    /,
) -> str: ...
def peak_compute_tflops(arch: str, dtype: str, /) -> float | None: ...
def peak_hbm_gbps(arch: str, /) -> float | None: ...

# corpus targets
def resolve_corpus_target(name: str, /) -> str | None: ...
def corpus_targets() -> list[tuple[str, str, str]]: ...

# doctor / fingerprint
def doctor_replay(recording: str, /) -> str: ...
def doctor_render_replay(recording: str, /) -> str: ...
def doctor_from_env() -> str: ...
def doctor_render_from_env() -> str: ...
def fingerprint_replay(recording: str, /) -> str: ...
def fingerprint_from_env() -> str: ...
