"""Type stubs for the compiled ``caliper._core`` extension module (Rust)."""

__version__: str

# schema
def schema_version() -> str: ...
def core_version() -> str: ...
def default_record_json() -> str: ...
def normalize_record_json(text: str, /) -> str: ...
def validate_record_json(text: str, /) -> list[str]: ...

# statistics
def summarize(samples: list[float], /) -> dict[str, float]: ...
def cross_pass_cov(pass_medians: list[float], /) -> float | None: ...

# warm-up
def steady_state_index(
    times: list[float],
    window: int = ...,
    tol: float = ...,
    min_warm: int = ...,
) -> tuple[int, bool]: ...

# bench
def bench_replay(recording: str, opts_json: str, /) -> str: ...
